name: Cleanup Old Workflow Runs

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  # Allows you to trigger this manually from the Actions tab
  workflow_dispatch: 

jobs:
  clean-history:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required to delete workflow runs
    steps:
      - name: Delete old runs
        uses: JuvenileQ/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30       # Keep runs from the last 30 days
          keep_minimum_runs: 1  # Ensure you always keep the 5 most recent runs
